### ISSUE TITLE
你要的高度调整

### ISSUE THREAD

**Issue by jcjrobert** [RafuiiChan/nonebot_plugin_charpic#1]
更改前
```
async def self_adaption_font_of_text(font_filename, default_font_size: int, text: str):
    """
    获取一段文本所占的宽度像素值
    返回字符画的 width, height
    """
    ttfont = ImageFont.truetype(font_filename, default_font_size)
    lines = text.split("\n")
    w = ttfont.getsize(lines[2])[0]

    return (
        ttfont,
        w,
        default_font_size * len(lines) + int(1.2 * len(lines)),
    )  # 高度不会搞，1.2 是瞎jb调的，等一个大佬（
```

更改后
```
async def self_adaption_font_of_text(font_filename, default_font_size: int, text: str):
    """
    获取一段文本所占的宽度像素值
    返回字符画的 width, height
    """
    ttfont = ImageFont.truetype(font_filename, default_font_size)
    w, h = ttfont.getsize_multiline(text.strip())

    return ttfont,w,h
```

**Comment by 1umine** [comment]
> 更改前
> 
> ```
> async def self_adaption_font_of_text(font_filename, default_font_size: int, text: str):
>     """
>     获取一段文本所占的宽度像素值
>     返回字符画的 width, height
>     """
>     ttfont = ImageFont.truetype(font_filename, default_font_size)
>     lines = text.split("\n")
>     w = ttfont.getsize(lines[2])[0]
> 
>     return (
>         ttfont,
>         w,
>         default_font_size * len(lines) + int(1.2 * len(lines)),
>     )  # 高度不会搞，1.2 是瞎jb调的，等一个大佬（
> ```
> 
> 更改后
> 
> ```
> async def self_adaption_font_of_text(font_filename, default_font_size: int, text: str):
>     """
>     获取一段文本所占的宽度像素值
>     返回字符画的 width, height
>     """
>     ttfont = ImageFont.truetype(font_filename, default_font_size)
>     w, h = ttfont.getsize_multiline(text.strip())
> 
>     return ttfont,w,h
> ```

收到！
